=== magfalk/webteknik3_ht22/L1/employees.dtd
<!-- 
company_employees
    location+
        attr: type(Stockholm|Göteborg|Malmö)
        descripton
        address
            street
            postal_code
            employee+
                name
                    first_name
                    last_name
            image*
                attr: url
                attr: caption
                    
-->
<!ELEMENT company_employees (location+)>
    <!ELEMENT location (description, address+)>
            <!ATTLIST location type (Stockholm|Göteborg|Malmö) #REQUIRED>
        <!ELEMENT description (#PCDATA)>        
        <!ELEMENT address (street, postal_code, employee+)>
            <!ELEMENT street (#PCDATA)>
            <!ELEMENT postal_code (#PCDATA)>
            <!ELEMENT employee (name+, image*)>
                <!ELEMENT name (first_name, last_name)>
                    <!ELEMENT first_name (#PCDATA)>
                    <!ELEMENT last_name (#PCDATA)>
                <!ELEMENT image EMPTY>
                    <!ATTLIST image url CDATA #REQUIRED caption CDATA #IMPLIED>

=== magfalk/webteknik3_ht22/L1/sthlm.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE company_employees SYSTEM "employees.dtd">
<company_employees>
    <location type="Stockholm">
        <description>
            Vi erbjuder finfina lokaler i centrala delarna av Stockhom
        </description>
        <address>
            <street>Kungsgatan 1
            </street>
            <postal_code>10001                
            </postal_code>
            <employee>
                <name>
                    <first_name>Sven
                    </first_name>
                    <last_name>Svensson
                    </last_name>
                </name>
                <image url="" caption="Not yet uploaded" />
            </employee>
        </address>
   </location>
   <location type="Stockholm">
    <description>Vi finns Ã¤ven i grannhuset
    </description>
    <address>
        <street>Kungsgatan 3
        </street>
        <postal_code>10001                
        </postal_code>
        <employee>
            <name>
                <first_name>Anders
                </first_name>
                <last_name>Andersson
                </last_name>
            </name>
            <image url="img/sthlm.jpg" caption="Stockholm" />
        </employee>
    </address>
</location>   
</company_employees>
